"""adding group   in sample 

Revision ID: 02660b29ceef
Revises: 1b9cce7ebbe6
Create Date: 2024-08-06 19:01:24.769940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02660b29ceef'
down_revision: Union[str, None] = '1b9cce7ebbe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('discipline', sa.String(), nullable=True))
    op.add_column('samples', sa.Column('group', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'group')
    op.drop_column('samples', 'discipline')
    # ### end Alembic commands ###
