"""add test method , reason, statement of conformity

Revision ID: 0488cd0b781c
Revises: 28812bc43da0
Create Date: 2024-09-01 19:19:33.186900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0488cd0b781c'
down_revision: Union[str, None] = '28812bc43da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('statement_of_conformity', sa.Text(), nullable=True))
    op.add_column('samples', sa.Column('reason', sa.Text(), nullable=True))
    op.add_column('samples', sa.Column('test_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'test_method')
    op.drop_column('samples', 'reason')
    op.drop_column('samples', 'statement_of_conformity')
    # ### end Alembic commands ###
