"""remove report send by

Revision ID: 0bc901de9d10
Revises: b195064a4c65
Create Date: 2024-07-13 10:21:51.397722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0bc901de9d10'
down_revision: Union[str, None] = 'b195064a4c65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'reports_send_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('reports_send_by', postgresql.ENUM('COURIER', 'EMAIL', name='reportsentbyenum', create_type=False), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
