"""sample addd samples received

Revision ID: 11fe0090535c
Revises: ff7a12ec734b
Create Date: 2024-07-22 22:16:06.690861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11fe0090535c'
down_revision: Union[str, None] = 'ff7a12ec734b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('samples_received', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'samples_received')
    # ### end Alembic commands ###
