"""front desk new changes

Revision ID: 171fb714d827
Revises: da3fc6fe9422
Create Date: 2024-06-18 21:24:09.887649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

# revision identifiers, used by Alembic.
revision: str = '171fb714d827'
down_revision: Union[str, None] = 'da3fc6fe9422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('frontdesks', 'deparment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.sync_enum_values('public', 'frontdeskstatus', ['UNDER_REGISTRATION', 'REGISTERED'],
                        [TableReference(table_schema='public', table_name='frontdesks', column_name='status')],
                        enum_values_to_rename=[])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'frontdeskstatus', ['NOT_REGISTRATION', 'REGISTRATION'],
                        [TableReference(table_schema='public', table_name='frontdesks', column_name='status')],
                        enum_values_to_rename=[])
    op.alter_column('frontdesks', 'deparment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
