"""Add contact and authorized person id in invoice

Revision ID: 1ab7605713f2
Revises: 99f0503ff3c3
Create Date: 2024-09-10 19:55:13.784597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ab7605713f2'
down_revision: Union[str, None] = '99f0503ff3c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('contact_person_name', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('contact_phone', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('authorized_sign_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'users', ['authorized_sign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'authorized_sign_id')
    op.drop_column('invoices', 'contact_phone')
    op.drop_column('invoices', 'contact_person_name')
    # ### end Alembic commands ###
