"""adding report no  in sample 

Revision ID: 1b9cce7ebbe6
Revises: b9689f10cf67
Create Date: 2024-08-05 17:49:57.827987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b9cce7ebbe6'
down_revision: Union[str, None] = 'b9689f10cf67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('report_no', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'report_no')
    # ### end Alembic commands ###
