"""status in sample

Revision ID: 20bb4a4b0e26
Revises: 4cadf510b568
Create Date: 2024-03-07 22:26:17.103235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20bb4a4b0e26'
down_revision: Union[str, None] = '4cadf510b568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sample_test_parameters', 'test_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('samples', sa.Column('status', sa.String(), nullable=True))
    op.alter_column('samples', 'registration_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('samples_status_id_fkey', 'samples', type_='foreignkey')
    op.create_foreign_key(None, 'samples', 'sample_status', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'samples', type_='foreignkey')
    op.create_foreign_key('samples_status_id_fkey', 'samples', 'users', ['status_id'], ['id'])
    op.alter_column('samples', 'registration_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('samples', 'status')
    op.alter_column('sample_test_parameters', 'test_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
