"""smaple table constraint

Revision ID: 20db9c85577f
Revises: fe8c02802c4d
Create Date: 2024-03-05 23:14:51.856446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20db9c85577f'
down_revision: Union[str, None] = 'fe8c02802c4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('samples', 'assigned_to',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('samples', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('testingparameters', 'parameter_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('testingparameters', 'parameter_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('samples', 'status_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('samples', 'assigned_to',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
