"""add more fields to front desk

Revision ID: 2846d2f1f101
Revises: 393f7b4e166b
Create Date: 2024-05-26 10:14:10.167719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2846d2f1f101'
down_revision: Union[str, None] = '393f7b4e166b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('NOT_REGISTRATION', 'REGISTRATION', name='frontdeskstatus').create(op.get_bind())
    sa.Enum('DAMAGED', 'GOOD', name='samplecondition').create(op.get_bind())
    sa.Enum('SAMPLE', 'Material', name='parceltype').create(op.get_bind())
    op.add_column('frontdesks', sa.Column('product_received', postgresql.ENUM('SAMPLE', 'Material', name='parceltype', create_type=False), nullable=False))
    op.add_column('frontdesks', sa.Column('sample_condition', postgresql.ENUM('DAMAGED', 'GOOD', name='samplecondition', create_type=False), nullable=False))
    op.add_column('frontdesks', sa.Column('temperature', sa.String(), nullable=False))
    op.add_column('frontdesks', sa.Column('deparment_id', sa.Integer(), nullable=False))
    op.add_column('frontdesks', sa.Column('status', postgresql.ENUM('NOT_REGISTRATION', 'REGISTRATION', name='frontdeskstatus', create_type=False), nullable=False))
    op.create_foreign_key(None, 'frontdesks', 'departments', ['deparment_id'], ['id'])
    sa.Enum('MECH', 'MICRO', name='department').drop(op.get_bind())
    sa.Enum('HOD', 'MARKETING', 'ADMIN', 'MANAGEMENT', 'ANALYST', name='roletype').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('HOD', 'MARKETING', 'ADMIN', 'MANAGEMENT', 'ANALYST', name='roletype').create(op.get_bind())
    sa.Enum('MECH', 'MICRO', name='department').create(op.get_bind())
    op.drop_constraint(None, 'frontdesks', type_='foreignkey')
    op.drop_column('frontdesks', 'status')
    op.drop_column('frontdesks', 'deparment_id')
    op.drop_column('frontdesks', 'temperature')
    op.drop_column('frontdesks', 'sample_condition')
    op.drop_column('frontdesks', 'product_received')
    sa.Enum('SAMPLE', 'Material', name='parceltype').drop(op.get_bind())
    sa.Enum('DAMAGED', 'GOOD', name='samplecondition').drop(op.get_bind())
    sa.Enum('NOT_REGISTRATION', 'REGISTRATION', name='frontdeskstatus').drop(op.get_bind())
    # ### end Alembic commands ###
