"""add show status and verified sign  in sample

Revision ID: 28812bc43da0
Revises: 90bd36eec75b
Create Date: 2024-08-30 21:19:01.667978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28812bc43da0'
down_revision: Union[str, None] = '90bd36eec75b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample_details', sa.Column('sign_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample_details', 'sign_verified')
    # ### end Alembic commands ###
