"""adding received quantity in sample detail

Revision ID: 2db0f00a4d04
Revises: 15b0600defb0
Create Date: 2024-08-01 20:49:54.559634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2db0f00a4d04'
down_revision: Union[str, None] = '15b0600defb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample_details', sa.Column('received_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample_details', 'received_quantity')
    # ### end Alembic commands ###
