"""sample workflow test types

Revision ID: 30cdea6ab165
Revises: cc4de2211b69
Create Date: 2024-07-28 21:57:36.168542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30cdea6ab165'
down_revision: Union[str, None] = 'cc4de2211b69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample_workflows', sa.Column('test_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sample_workflows', 'testtypes', ['test_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sample_workflows', type_='foreignkey')
    op.drop_column('sample_workflows', 'test_type_id')
    # ### end Alembic commands ###
