"""sample workflow test types1

Revision ID: 3125b8a8226f
Revises: 704ec2e4eb0b
Create Date: 2024-07-30 13:23:03.321555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3125b8a8226f'
down_revision: Union[str, None] = '704ec2e4eb0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('samples', 'test_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('samples', 'test_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
