"""add description in sample

Revision ID: 4c5ae2d3cc7f
Revises: ac89c4e3a687
Create Date: 2024-07-11 19:02:01.231205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c5ae2d3cc7f'
down_revision: Union[str, None] = 'ac89c4e3a687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'description')
    # ### end Alembic commands ###
