"""add front desk id to registrations

Revision ID: 76fe7fc87f47
Revises: 171fb714d827
Create Date: 2024-06-22 19:12:43.944380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76fe7fc87f47'
down_revision: Union[str, None] = '171fb714d827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('front_desk_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'registrations', 'frontdesks', ['front_desk_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.drop_column('registrations', 'front_desk_id')
    # ### end Alembic commands ###
