"""add unit in sample test parameter

Revision ID: 788dfb178b7f
Revises: ff9be9f9eb37
Create Date: 2024-08-13 20:55:57.385944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '788dfb178b7f'
down_revision: Union[str, None] = 'ff9be9f9eb37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample_test_parameters', sa.Column('unit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample_test_parameters', 'unit')
    # ### end Alembic commands ###
