"""add status in invoice

Revision ID: 78d1423cfab1
Revises: fb915a2c5057
Create Date: 2024-09-06 22:13:43.368694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78d1423cfab1'
down_revision: Union[str, None] = 'fb915a2c5057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'status')
    # ### end Alembic commands ###
