"""check new changes

Revision ID: 79c372f18545
Revises: 2846d2f1f101
Create Date: 2024-05-26 22:05:08.323461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79c372f18545'
down_revision: Union[str, None] = '2846d2f1f101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('branches', 'branch_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_branches_branch_name'), 'branches', ['branch_name'], unique=True)
    op.add_column('registrations', sa.Column('trf_code', sa.String(), nullable=True))
    op.add_column('registrations', sa.Column('nabl_logo', sa.Boolean(), nullable=False))
    op.add_column('registrations', sa.Column('batch_or_lot_no', sa.String(), nullable=False))
    op.add_column('registrations', sa.Column('manufactured_date', sa.Date(), nullable=False))
    op.add_column('registrations', sa.Column('expiry_date', sa.Date(), nullable=False))
    op.add_column('registrations', sa.Column('batch_size', sa.Integer(), nullable=False))
    op.add_column('registrations', sa.Column('no_of_samples', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'no_of_samples')
    op.drop_column('registrations', 'batch_size')
    op.drop_column('registrations', 'expiry_date')
    op.drop_column('registrations', 'manufactured_date')
    op.drop_column('registrations', 'batch_or_lot_no')
    op.drop_column('registrations', 'nabl_logo')
    op.drop_column('registrations', 'trf_code')
    op.drop_index(op.f('ix_branches_branch_name'), table_name='branches')
    op.alter_column('branches', 'branch_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
