"""removed abbr

Revision ID: 7def23d7b408
Revises: f0d753db0891
Create Date: 2024-09-12 21:26:15.333199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7def23d7b408'
down_revision: Union[str, None] = 'f0d753db0891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'abbreviations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('abbreviations', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
