"""alter field name in sample

Revision ID: 827c724bc6b9
Revises: 179a4aa64de3
Create Date: 2024-07-21 19:04:31.102221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '827c724bc6b9'
down_revision: Union[str, None] = '179a4aa64de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('sterilization_batch_no', sa.String(), nullable=True))
    op.drop_column('samples', 'Sterilization_batch_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('Sterilization_batch_no', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('samples', 'sterilization_batch_no')
    # ### end Alembic commands ###
