"""workflow chnages

Revision ID: 839c8c533f33
Revises: 0f8de80b51cf
Create Date: 2024-03-17 20:26:53.880795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '839c8c533f33'
down_revision: Union[str, None] = '0f8de80b51cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample_status', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('sample_status', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('sample_status', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sample_status', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'sample_status', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(None, 'sample_status', 'roles', ['role_id'], ['id'])
    op.add_column('sample_workflows', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('sample_workflows', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sample_workflows', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'sample_workflows', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sample_workflows', type_='foreignkey')
    op.drop_constraint(None, 'sample_workflows', type_='foreignkey')
    op.drop_column('sample_workflows', 'role_id')
    op.drop_column('sample_workflows', 'department_id')
    op.drop_constraint(None, 'sample_status', type_='foreignkey')
    op.drop_constraint(None, 'sample_status', type_='foreignkey')
    op.drop_constraint(None, 'sample_status', type_='foreignkey')
    op.drop_column('sample_status', 'user_id')
    op.drop_column('sample_status', 'role_id')
    op.drop_column('sample_status', 'department_id')
    # ### end Alembic commands ###
