"""front desk field name change

Revision ID: 84aa9e6a3964
Revises: 83b52f9f3f72
Create Date: 2024-05-29 10:25:13.412122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84aa9e6a3964'
down_revision: Union[str, None] = '83b52f9f3f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frontdesks', sa.Column('parcel_received', postgresql.ENUM('SAMPLE', 'Material', name='parceltype', create_type=False), nullable=False))
    op.drop_column('frontdesks', 'product_received')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frontdesks', sa.Column('product_received', postgresql.ENUM('SAMPLE', 'Material', name='parceltype', create_type=False), autoincrement=False, nullable=False))
    op.drop_column('frontdesks', 'parcel_received')
    # ### end Alembic commands ###
