"""add test abbreviations and signed date

Revision ID: 8bb85cf0b32c
Revises: 0488cd0b781c
Create Date: 2024-09-03 18:52:34.582992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bb85cf0b32c'
down_revision: Union[str, None] = '0488cd0b781c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample_details', sa.Column('authorized_sign_date', sa.Date(), nullable=True))
    op.add_column('samples', sa.Column('abreviations', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'abreviations')
    op.drop_column('sample_details', 'authorized_sign_date')
    # ### end Alembic commands ###
