"""Add igst column to invoice table

Revision ID: 8becc6e22494
Revises: c1a99077e476
Create Date: 2024-09-09 19:13:30.764628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8becc6e22494'
down_revision: Union[str, None] = 'c1a99077e476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('igst', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'igst')
    # ### end Alembic commands ###
