"""add show status  in sample

Revision ID: 90bd36eec75b
Revises: c7f0b549e455
Create Date: 2024-08-26 21:34:47.653753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90bd36eec75b'
down_revision: Union[str, None] = 'c7f0b549e455'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('show_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'show_status')
    # ### end Alembic commands ###
