"""Branch Migration v2

Revision ID: 91bd3a32834b
Revises: b97ef14925d1
Create Date: 2024-02-14 12:04:59.206368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91bd3a32834b'
down_revision: Union[str, None] = 'b97ef14925d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('branches', 'branch_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('branches', 'address_line1',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('branches', 'address_line2',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('branches', 'mobile_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('branches', 'landline_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('branches', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('branches', 'pan_no',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('branches', 'cin',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('branches', 'gstin',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('branches', 'bank_details',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('branches', 'ifsc_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_branches_branch_name'), 'branches', ['branch_name'], unique=True)
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_branches_id'), table_name='branches')
    op.drop_index(op.f('ix_branches_branch_name'), table_name='branches')
    op.alter_column('branches', 'ifsc_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('branches', 'bank_details',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('branches', 'gstin',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('branches', 'cin',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('branches', 'pan_no',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('branches', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('branches', 'landline_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('branches', 'mobile_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('branches', 'address_line2',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('branches', 'address_line1',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('branches', 'branch_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
