"""sample updates

Revision ID: 927afa080230
Revises: 20bb4a4b0e26
Create Date: 2024-03-08 23:27:46.190585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '927afa080230'
down_revision: Union[str, None] = '20bb4a4b0e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample_history', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sample_history', 'users', ['assigned_to'], ['id'])
    op.alter_column('sample_workflows', 'assigned_to',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### commands auto generated by Alembic - please adjust! ###
    departmenttype_enum = postgresql.ENUM('MECH', 'MICRO', name='department', create_type=False)
    departmenttype_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('samples', sa.Column('department', departmenttype_enum, nullable=True))
    op.add_column('users', sa.Column('department', departmenttype_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'department')
    op.drop_column('samples', 'department')
    op.alter_column('sample_workflows', 'assigned_to',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'sample_history', type_='foreignkey')
    op.drop_column('sample_history', 'assigned_to')
    # ### end Alembic commands ###
