"""batch product_id optional

Revision ID: 9e5b2960db1e
Revises: 7da7e3e2c796
Create Date: 2024-05-17 21:45:35.066022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e5b2960db1e'
down_revision: Union[str, None] = '7da7e3e2c796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'batches', 'products', ['product_id'], ['id'])
    op.add_column('samples', sa.Column('registration_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'samples', 'registrations', ['registration_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'samples', type_='foreignkey')
    op.drop_column('samples', 'registration_id')
    op.drop_constraint(None, 'batches', type_='foreignkey')
    op.drop_column('batches', 'product_id')
    # ### end Alembic commands ###
