"""update on registrations fields2

Revision ID: 9e7e9cb652ae
Revises: 4c162de4191c
Create Date: 2024-07-01 21:49:33.995078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e7e9cb652ae'
down_revision: Union[str, None] = '4c162de4191c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('UNDER_REGISTRATION', 'REGISTERED', name='registrationstatus').create(op.get_bind())
    op.add_column('registrations', sa.Column('status', postgresql.ENUM('UNDER_REGISTRATION', 'REGISTERED', name='registrationstatus', create_type=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'status')
    sa.Enum('UNDER_REGISTRATION', 'REGISTERED', name='registrationstatus').drop(op.get_bind())
    # ### end Alembic commands ###
