"""add abbr list

Revision ID: 9f878987c57a
Revises: 7def23d7b408
Create Date: 2024-09-12 21:27:15.936643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f878987c57a'
down_revision: Union[str, None] = '7def23d7b408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('abbreviations', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'abbreviations')
    # ### end Alembic commands ###
