"""checking for updates

Revision ID: aa94c3e23ad8
Revises: 839c8c533f33
Create Date: 2024-03-23 18:17:48.964766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa94c3e23ad8'
down_revision: Union[str, None] = '839c8c533f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('test_type_id', sa.Integer(), nullable=True))
    op.drop_constraint('samples_department_id_fkey', 'samples', type_='foreignkey')
    op.create_foreign_key(None, 'samples', 'testtypes', ['test_type_id'], ['id'])
    op.drop_column('samples', 'department_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'samples', type_='foreignkey')
    op.create_foreign_key('samples_department_id_fkey', 'samples', 'testtypes', ['department_id'], ['id'])
    op.drop_column('samples', 'test_type_id')
    # ### end Alembic commands ###
