"""add invoice ad status id

Revision ID: aabb21183830
Revises: 23ac31b9dd02
Create Date: 2024-09-06 20:12:04.031172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aabb21183830'
down_revision: Union[str, None] = '23ac31b9dd02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'invoice_status', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'status_id')
    # ### end Alembic commands ###
