"""remove parcel_received

Revision ID: ae43eb2da9c4
Revises: da5a9a09b03a
Create Date: 2024-06-10 18:54:56.076526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae43eb2da9c4'
down_revision: Union[str, None] = 'da5a9a09b03a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('frontdesks', 'parcel_received')
    sa.Enum('SAMPLE', 'Material', name='parceltype').drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('SAMPLE', 'Material', name='parceltype').create(op.get_bind())
    op.add_column('frontdesks', sa.Column('parcel_received', postgresql.ENUM('SAMPLE', 'Material', name='parceltype', create_type=False), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
