"""test type added in registration2

Revision ID: b4a560dc3088
Revises: 7ad125b62d22
Create Date: 2024-03-25 14:15:05.610634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4a560dc3088'
down_revision: Union[str, None] = '7ad125b62d22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration_test_types', sa.Column('test_type_id', sa.Integer(), nullable=False))
    op.drop_constraint('registration_test_types_test_params_id_fkey', 'registration_test_types', type_='foreignkey')
    op.create_foreign_key(None, 'registration_test_types', 'testtypes', ['test_type_id'], ['id'])
    op.drop_column('registration_test_types', 'test_params_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration_test_types', sa.Column('test_params_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'registration_test_types', type_='foreignkey')
    op.create_foreign_key('registration_test_types_test_params_id_fkey', 'registration_test_types', 'testingparameters', ['test_params_id'], ['id'])
    op.drop_column('registration_test_types', 'test_type_id')
    # ### end Alembic commands ###
