"""add test abbreviations name corrections

Revision ID: b59135f8e948
Revises: 8bb85cf0b32c
Create Date: 2024-09-03 19:20:28.993430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b59135f8e948'
down_revision: Union[str, None] = '8bb85cf0b32c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('abbreviations', sa.String(), nullable=True))
    op.drop_column('samples', 'abreviations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('abreviations', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('samples', 'abbreviations')
    # ### end Alembic commands ###
