"""change contact person email to contact_email

Revision ID: b97ef14925d1
Revises: c01be0c8b234
Create Date: 2024-01-22 12:30:49.841496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b97ef14925d1'
down_revision: Union[str, None] = 'c01be0c8b234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contactpersons', sa.Column('contact_email', sa.String(), nullable=True))
    op.drop_column('contactpersons', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contactpersons', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('contactpersons', 'contact_email')
    # ### end Alembic commands ###
