"""adding specification_limits  in sample test parameter 

Revision ID: b9d9adde24af
Revises: 02660b29ceef
Create Date: 2024-08-08 20:18:19.200630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9d9adde24af'
down_revision: Union[str, None] = '02660b29ceef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample_test_parameters', sa.Column('specification_limits', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample_test_parameters', 'specification_limits')
    # ### end Alembic commands ###
