"""sample history test types1

Revision ID: bdb7e7f3d6c2
Revises: 3125b8a8226f
Create Date: 2024-07-30 14:21:24.348747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdb7e7f3d6c2'
down_revision: Union[str, None] = '3125b8a8226f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample_history', sa.Column('test_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sample_history', 'testtypes', ['test_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sample_history', type_='foreignkey')
    op.drop_column('sample_history', 'test_type_id')
    # ### end Alembic commands ###
