"""add additional details in sample

Revision ID: c7f0b549e455
Revises: 1126932b7908
Create Date: 2024-08-24 20:20:26.451058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7f0b549e455'
down_revision: Union[str, None] = '1126932b7908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('additional_detail', sa.Text(), nullable=True))
    op.alter_column('testtype_association', 'test_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('testtype_association', 'test_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('samples', 'additional_detail')
    # ### end Alembic commands ###
