"""modify fields

Revision ID: cdefdedc5fad
Revises: ae43eb2da9c4
Create Date: 2024-06-14 12:49:38.929852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdefdedc5fad'
down_revision: Union[str, None] = 'ae43eb2da9c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration_test_parameters', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('registrations', sa.Column('controlled_quantity', sa.Integer(), nullable=True))
    op.alter_column('registrations', 'test_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('sample_test_parameters', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample_test_parameters', 'quantity')
    op.alter_column('registrations', 'test_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('registrations', 'controlled_quantity')
    op.drop_column('registration_test_parameters', 'quantity')
    # ### end Alembic commands ###
