"""no more fields changes  

Revision ID: cf3657924cf5
Revises: b9d9adde24af
Create Date: 2024-08-09 20:02:53.632627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf3657924cf5'
down_revision: Union[str, None] = 'b9d9adde24af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frontdesks', sa.Column('no_of_boxes_received', sa.String(), nullable=True))
    op.alter_column('samples', 'received_quantity',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('testingparameters', sa.Column('specification_limits', sa.String(), nullable=True))
    op.add_column('testingparameters', sa.Column('min_limits', sa.String(), nullable=True))
    op.add_column('testingparameters', sa.Column('max_limits', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testingparameters', 'max_limits')
    op.drop_column('testingparameters', 'min_limits')
    op.drop_column('testingparameters', 'specification_limits')
    op.alter_column('samples', 'received_quantity',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('frontdesks', 'no_of_boxes_received')
    # ### end Alembic commands ###
