"""add test show status to show_status_report name corrections

Revision ID: d0291a7df3df
Revises: b59135f8e948
Create Date: 2024-09-03 19:23:29.656639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0291a7df3df'
down_revision: Union[str, None] = 'b59135f8e948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('show_status_report', sa.Boolean(), nullable=True))
    op.drop_column('samples', 'show_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('show_status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('samples', 'show_status_report')
    # ### end Alembic commands ###
