"""menus changes4

Revision ID: d142e28ca186
Revises: 960b0e08027c
Create Date: 2024-03-16 14:28:09.594003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd142e28ca186'
down_revision: Union[str, None] = '960b0e08027c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_control_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('samples_department_id_fkey', 'samples', type_='foreignkey')
    op.create_foreign_key(None, 'samples', 'testtypes', ['department_id'], ['id'])
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('qa_type_id', sa.Integer(), nullable=True))
    op.drop_constraint('users_department_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    op.create_foreign_key(None, 'users', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(None, 'users', 'testtypes', ['qa_type_id'], ['id'])
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('HOD', 'MARKETING', 'ADMIN', 'MANAGEMENT', 'ANALYST', name='roletype'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_department_id_fkey', 'users', 'testingparameters', ['department_id'], ['id'])
    op.drop_column('users', 'qa_type_id')
    op.drop_column('users', 'role_id')
    op.drop_constraint(None, 'samples', type_='foreignkey')
    op.create_foreign_key('samples_department_id_fkey', 'samples', 'testingparameters', ['department_id'], ['id'])
    op.drop_table('menu_control_lists')
    op.drop_table('roles')
    op.drop_table('menus')
    op.drop_table('departments')
    # ### end Alembic commands ###
