"""add designation in user 

Revision ID: d36cb831211a
Revises: cf3657924cf5
Create Date: 2024-08-09 21:55:28.884699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd36cb831211a'
down_revision: Union[str, None] = 'cf3657924cf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('designation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'designation')
    # ### end Alembic commands ###
