"""new fields on samples again

Revision ID: d60f0455ca05
Revises: f90f7f27887a
Create Date: 2024-07-21 17:57:42.599610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd60f0455ca05'
down_revision: Union[str, None] = 'f90f7f27887a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('sample_issued', sa.Integer(), nullable=True))
    op.add_column('samples', sa.Column('issued_to', sa.String(), nullable=True))
    op.add_column('samples', sa.Column('sample_condition', sa.String(), nullable=True))
    op.add_column('samples', sa.Column('Sterilization_batch_no', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'Sterilization_batch_no')
    op.drop_column('samples', 'sample_condition')
    op.drop_column('samples', 'issued_to')
    op.drop_column('samples', 'sample_issued')
    # ### end Alembic commands ###
