"""auto generate code

Revision ID: d65065ec5fb5
Revises: aa94c3e23ad8
Create Date: 2024-03-25 11:08:52.835234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65065ec5fb5'
down_revision: Union[str, None] = 'aa94c3e23ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'code')
    # ### end Alembic commands ###
