"""Auto Column Change Check 1

Revision ID: d978132d96d7
Revises: 411e0c7daaed
Create Date: 2024-05-15 19:42:10.810676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd978132d96d7'
down_revision: Union[str, None] = '411e0c7daaed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('batches_registration_id_fkey', 'batches', type_='foreignkey')
    op.drop_column('batches', 'registration_id')
    op.alter_column('registrations', 'trf_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registrations', 'trf_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('batches', sa.Column('registration_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('batches_registration_id_fkey', 'batches', 'registrations', ['registration_id'], ['id'])
    # ### end Alembic commands ###
