"""add received by

Revision ID: da3fc6fe9422
Revises: cdefdedc5fad
Create Date: 2024-06-14 21:12:36.908865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da3fc6fe9422'
down_revision: Union[str, None] = 'cdefdedc5fad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frontdesks', sa.Column('received_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'frontdesks', 'users', ['received_by'], ['id'])
    op.alter_column('samples', 'test_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('samples', 'test_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'frontdesks', type_='foreignkey')
    op.drop_column('frontdesks', 'received_by')
    # ### end Alembic commands ###
