"""add new fields in registrations

Revision ID: df48d33c394d
Revises: 827c724bc6b9
Create Date: 2024-07-21 21:00:01.314192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df48d33c394d'
down_revision: Union[str, None] = '827c724bc6b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('customer_reference_no', sa.String(), nullable=True))
    op.add_column('registrations', sa.Column('contact_person_name', sa.String(), nullable=True))
    op.add_column('registrations', sa.Column('contact_email', sa.String(), nullable=True))
    op.add_column('registrations', sa.Column('contact_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'contact_number')
    op.drop_column('registrations', 'contact_email')
    op.drop_column('registrations', 'contact_person_name')
    op.drop_column('registrations', 'customer_reference_no')
    # ### end Alembic commands ###
