"""followup history

Revision ID: e07d63621d23
Revises: a5d97942a987
Create Date: 2024-03-27 09:36:07.792628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e07d63621d23'
down_revision: Union[str, None] = 'a5d97942a987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customerfollowups_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_followup_id', sa.Integer(), nullable=True),
    sa.Column('marketing_status', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_followup_id'], ['customerfollowups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customerfollowups_history')
    # ### end Alembic commands ###
