"""commnet nullable

Revision ID: e212a5604533
Revises: e07d63621d23
Create Date: 2024-03-28 14:19:52.254137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e212a5604533'
down_revision: Union[str, None] = 'e07d63621d23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sample_history', 'comments',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sample_history', 'comments',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
