"""new fields on sample

Revision ID: e453cd920a05
Revises: bf4117b70318
Create Date: 2024-07-15 20:18:01.136695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e453cd920a05'
down_revision: Union[str, None] = 'bf4117b70318'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('testing_start_date', sa.Date(), nullable=True))
    op.add_column('samples', sa.Column('testing_end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'testing_end_date')
    op.drop_column('samples', 'testing_start_date')
    # ### end Alembic commands ###
