"""why more fieds on sample test parameters

Revision ID: eda194259c6e
Revises: d36cb831211a
Create Date: 2024-08-12 18:56:16.330435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eda194259c6e'
down_revision: Union[str, None] = 'd36cb831211a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample_test_parameters', sa.Column('max_limits', sa.String(), nullable=True))
    op.add_column('sample_test_parameters', sa.Column('min_limits', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample_test_parameters', 'min_limits')
    op.drop_column('sample_test_parameters', 'max_limits')
    # ### end Alembic commands ###
