"""Add invoice_mode null in invoice

Revision ID: f0d753db0891
Revises: 1ab7605713f2
Create Date: 2024-09-12 18:40:18.028929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0d753db0891'
down_revision: Union[str, None] = '1ab7605713f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('invoice_mode', sa.String(), nullable=True))
    op.add_column('samples', sa.Column('genreate_report_no', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'genreate_report_no')
    op.drop_column('invoices', 'invoice_mode')
    # ### end Alembic commands ###
