"""samples upadte

Revision ID: f360a5220bfe
Revises: 8ab2d08148fa
Create Date: 2024-02-16 00:01:16.898354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f360a5220bfe'
down_revision: Union[str, None] = '8ab2d08148fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('registration_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'samples', 'registrations', ['registration_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'samples', type_='foreignkey')
    op.drop_column('samples', 'registration_id')
    # ### end Alembic commands ###
