"""add customer_id to batch

Revision ID: f6c041106c56
Revises: 9e5b2960db1e
Create Date: 2024-05-18 09:30:22.796725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6c041106c56'
down_revision: Union[str, None] = '9e5b2960db1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'batches', 'products', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'batches', type_='foreignkey')
    op.drop_column('batches', 'customer_id')
    # ### end Alembic commands ###
