"""add invoices

Revision ID: f7ece765b4c9
Revises: d0291a7df3df
Create Date: 2024-09-05 21:13:08.776054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7ece765b4c9'
down_revision: Union[str, None] = 'd0291a7df3df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_code', sa.String(), nullable=True),
    sa.Column('invoice_type', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_address', sa.Text(), nullable=False),
    sa.Column('customer_email', sa.String(), nullable=False),
    sa.Column('customer_gst', sa.String(), nullable=False),
    sa.Column('customer_ref_no', sa.String(), nullable=False),
    sa.Column('quotation_ref_no', sa.String(), nullable=False),
    sa.Column('sample_id_nos', sa.String(), nullable=False),
    sa.Column('sub_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sgst', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cgst', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('tested_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_test_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('test_parameter', sa.String(), nullable=False),
    sa.Column('sac', sa.String(), nullable=False),
    sa.Column('no_of_tested', sa.String(), nullable=False),
    sa.Column('testing_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_testing_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_test_parameters')
    op.drop_table('invoices')
    # ### end Alembic commands ###
