"""new fields on sample2

Revision ID: f90f7f27887a
Revises: e453cd920a05
Create Date: 2024-07-17 19:27:10.369104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f90f7f27887a'
down_revision: Union[str, None] = 'e453cd920a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('nabl_logo', sa.Boolean(), nullable=True))
    op.add_column('samples', sa.Column('under_cdsco', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'under_cdsco')
    op.drop_column('samples', 'nabl_logo')
    # ### end Alembic commands ###
