"""add lut_arn in invoice

Revision ID: fb915a2c5057
Revises: aabb21183830
Create Date: 2024-09-06 20:28:59.608765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb915a2c5057'
down_revision: Union[str, None] = 'aabb21183830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('lut_arn', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'lut_arn')
    # ### end Alembic commands ###
