"""add product_id to customer followup

Revision ID: fd63fa20635f
Revises: 7f4f8f685d89
Create Date: 2024-01-17 21:53:36.978637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd63fa20635f'
down_revision: Union[str, None] = '7f4f8f685d89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customerfollowups', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customerfollowups', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customerfollowups', type_='foreignkey')
    op.drop_column('customerfollowups', 'product_id')
    # ### end Alembic commands ###
