"""Adding sample workflow tables2

Revision ID: fe8c02802c4d
Revises: 7999b7103e1b
Create Date: 2024-03-03 20:49:37.429847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe8c02802c4d'
down_revision: Union[str, None] = '7999b7103e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registration_test_parameters', 'test_params_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sample_test_parameters', 'test_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sample_test_parameters', 'test_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('registration_test_parameters', 'test_params_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
