"""add manufactured by in registration

Revision ID: ff9be9f9eb37
Revises: eda194259c6e
Create Date: 2024-08-13 10:17:42.976422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff9be9f9eb37'
down_revision: Union[str, None] = 'eda194259c6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('manufactured_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'manufactured_by')
    # ### end Alembic commands ###
